# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise
locale: "en-US"
title: Mikko Lauri
title_separator: "|"
name: "Mikko Lauri"
description: >- # this means to ignore newlines until "baseurl:"
  Researcher in Computer Science and Robotics. Multi-agent 
  decision-making under uncertainty, active perception, 
  and deep learning for robot vision.

email: lauri@informatik.uni-hamburg.de

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://laurimi.github.io" # the base hostname & protocol for your site, e.g. http://example.com


masthead_title: "Mikko Lauri"
og_image: /assets/images/bio-photo.png

paginate: 5 # amount of posts to show
paginate_path: /page:num/


include: ["_pages"]


author:
  name     : "Mikko Lauri"
  avatar   : "/assets/images/bio-photo.png"
  bio      : "Researcher in Computer Science and Robotics. Multi-agent decision-making under uncertainty, active perception, 
  and deep learning for robot vision."
  location : "Hamburg, Germany"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/laurimi"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/mikko_lauri"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar ai"
      url: "https://scholar.google.com/citations?user=Ark4dHoAAAAJ"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      share: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true


# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-scholar

scholar:
  style: apa
  bibliography_template: bib
  repository: ./repository
